// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqzDNkSpZwz0xU8kTTZ1S29eUjZ_w0i-A',
    appId: '1:121096434805:web:610a2c5e846dacba39743c',
    messagingSenderId: '121096434805',
    projectId: 'wakeflow-5b260',
    authDomain: 'wakeflow-5b260.firebaseapp.com',
    storageBucket: 'wakeflow-5b260.firebasestorage.app',
    measurementId: 'G-WYLQ812ERK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6N3nvJ781EbMrIjlA_Y_P86mD4fIbUEU',
    appId: '1:121096434805:android:0bd2f39e511fafbf39743c',
    messagingSenderId: '121096434805',
    projectId: 'wakeflow-5b260',
    storageBucket: 'wakeflow-5b260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZiA2sCM2jnffw8KnBLkSOEKKuZcfuxeo',
    appId: '1:121096434805:ios:c6603c06e752c75239743c',
    messagingSenderId: '121096434805',
    projectId: 'wakeflow-5b260',
    storageBucket: 'wakeflow-5b260.firebasestorage.app',
    iosBundleId: 'com.example.wakeflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZiA2sCM2jnffw8KnBLkSOEKKuZcfuxeo',
    appId: '1:121096434805:ios:c6603c06e752c75239743c',
    messagingSenderId: '121096434805',
    projectId: 'wakeflow-5b260',
    storageBucket: 'wakeflow-5b260.firebasestorage.app',
    iosBundleId: 'com.example.wakeflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqzDNkSpZwz0xU8kTTZ1S29eUjZ_w0i-A',
    appId: '1:121096434805:web:db1d2e0972855cf639743c',
    messagingSenderId: '121096434805',
    projectId: 'wakeflow-5b260',
    authDomain: 'wakeflow-5b260.firebaseapp.com',
    storageBucket: 'wakeflow-5b260.firebasestorage.app',
    measurementId: 'G-FZVB35JGS1',
  );
}
